### ISSUE TITLE
I have some question about the repository.

### ISSUE THREAD

**Issue by Aaron2Woo** [LeErnst/MI2ML_NumExp#1]
Hey man, I‘m really interested in the FITNETS.
So, I haved clone your code and test it, the output is like your source. But I have some question about the repository.
1. I don't think this code is function of FITNETS, published in ICLR-2015 by Adriana Romero etc.
2. Is it just a simple CIFAR-10 classification task that the model design by yourself, but the accuracy is not good.
3.  If you also interested in FITNETS, I want to communication with you.

wechat number: 18721982017
email: 569911638@qq.com

**Comment by LeErnst** [comment]
Hey, this repository was created for an exam in a study course. But I didn't have enough time to figure out why the net doesn't work as expected. Although, the primary goal was testing the initialization procedures like Xavier-initialization and not the fitnets themselves. Moreover the repository is now closed. But thanks for your interest.
